apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml 
  - postgres/postgres-pvc.yaml      
  - postgres/postgres-secret.yaml   
  - postgres/postgres-deployment.yaml
  - monitoring 
  - #security/postgres-external-secret.yaml
  - #security/vault-cluster-store.yaml
  - infrastructure/external-secrets-app.yaml
  - infrastructure/vault-app.yaml
