apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret # El nombre del secreto que tus pods van a leer
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: database/postgres
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: database/postgres
        property: password